# Generated by Django 3.2.8 on 2022-06-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.FileField(upload_to='documents/')),
                ('user', models.CharField(choices=[('user', 'mainuser')], max_length=50)),
                ('about_heading', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('resume', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='contactmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_email', models.CharField(max_length=50)),
                ('sender_subject', models.CharField(max_length=100)),
                ('sender_message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='main_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('user', 'mainuser')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('background_img', models.FileField(upload_to='documents/')),
                ('emailid', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend360pimg', models.FileField(upload_to='documents/')),
                ('frontend720pimg', models.FileField(upload_to='documents/')),
                ('frontend1080pimg', models.FileField(upload_to='documents/')),
                ('adminloginimg', models.FileField(upload_to='documents/')),
                ('adminpanelimg', models.FileField(upload_to='documents/')),
                ('aboutproject1', models.CharField(max_length=500)),
                ('aboutproject2', models.CharField(max_length=500)),
                ('aboutproject3', models.CharField(max_length=500)),
                ('aboutproject4', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillid', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, unique=True)),
                ('logo', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('skill_description', models.CharField(max_length=50)),
            ],
        ),
    ]
